"""drop legacy tables from old version

Revision ID: 2ea4743f8fa7
Revises: a6c4d8e2f9b1
Create Date: 2026-07-11 12:38:10.469846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ea4743f8fa7'
down_revision: Union[str, Sequence[str], None] = 'a6c4d8e2f9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('daily_plans')
    op.drop_table('weekly_plans')
    op.drop_table('semester_settings')
    op.drop_table('prompts')
    op.drop_table('ai_call_logs')
    op.drop_table('ai_config')
    op.drop_table('app_settings')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_date', sa.DATE(), nullable=False, comment='计划日期'),
    sa.Column('week_number', mysql.INTEGER(), autoincrement=False, nullable=True, comment='第几周'),
    sa.Column('day_of_week', mysql.VARCHAR(length=10), nullable=True, comment='星期几（中文）'),
    sa.Column('grade', mysql.VARCHAR(length=20), nullable=True, comment='年级'),
    sa.Column('class_name', mysql.VARCHAR(length=20), nullable=True, comment='班级'),
    sa.Column('semester_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学期ID（FK）'),
    sa.Column('morning_activity_json', mysql.JSON(), nullable=True, comment='晨间活动所有字段'),
    sa.Column('morning_talk_json', mysql.JSON(), nullable=True, comment='晨间谈话所有字段'),
    sa.Column('group_activity_json', mysql.JSON(), nullable=True, comment='集体活动所有字段'),
    sa.Column('indoor_area_json', mysql.JSON(), nullable=True, comment='室内区域活动所有字段'),
    sa.Column('outdoor_game_json', mysql.JSON(), nullable=True, comment='户外游戏活动所有字段'),
    sa.Column('daily_reflection', mysql.TEXT(), nullable=True, comment='一日活动反思'),
    sa.Column('original_lesson_text', mysql.LONGTEXT(), nullable=True, comment='原始教案文本'),
    sa.Column('ai_modified_parts_json', mysql.JSON(), nullable=True, comment='AI修改部分（用于红色标记）'),
    sa.Column('status', mysql.ENUM('draft', 'completed'), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester_settings.id'], name=op.f('daily_plans_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='每日活动计划',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='每日活动计划',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_plan_date_grade_class'), ['plan_date', 'grade', 'class_name'], unique=True)

    op.create_table('prompts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt_name', mysql.VARCHAR(length=100), nullable=False, comment='提示词名称'),
    sa.Column('prompt_category', mysql.VARCHAR(length=50), nullable=False, comment='分类：lesson_split/daily_plan/morning_activity等'),
    sa.Column('prompt_content', mysql.LONGTEXT(), nullable=False, comment='提示词内容（支持占位符变量）'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='提示词管理',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='提示词管理',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ai_config',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_url', mysql.VARCHAR(length=500), nullable=False, comment='AI API 地址'),
    sa.Column('api_key', mysql.VARCHAR(length=1000), nullable=False, comment='API Key（加密存储）'),
    sa.Column('model_name', mysql.VARCHAR(length=100), nullable=False, comment='模型名称'),
    sa.Column('is_global', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='是否为全局配置'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='用户ID（预留，单用户版为NULL）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('weight', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='负载均衡权重（越大分配概率越高）'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI配置',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='AI配置',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ai_call_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=60), nullable=True, comment='调用分类：lesson_split/process_modify/morning_activity 等'),
    sa.Column('model_name', mysql.VARCHAR(length=100), nullable=True, comment='使用的模型名称'),
    sa.Column('prompt_text', mysql.LONGTEXT(), nullable=True, comment='发送的 prompt（user message）'),
    sa.Column('response_text', mysql.LONGTEXT(), nullable=True, comment='AI 返回的原始响应'),
    sa.Column('status', mysql.ENUM('success', 'error'), server_default=sa.text("'success'"), nullable=True),
    sa.Column('error_msg', mysql.TEXT(), nullable=True, comment='错误信息（status=error 时）'),
    sa.Column('duration_ms', mysql.INTEGER(), autoincrement=False, nullable=True, comment='耗时（毫秒）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 调用日志',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='AI 调用日志',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('semester_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester_name', mysql.VARCHAR(length=50), nullable=False, comment='学期名称，如 2025-2026学年第二学期'),
    sa.Column('start_date', sa.DATE(), nullable=False, comment='学期开始日期'),
    sa.Column('end_date', sa.DATE(), nullable=False, comment='学期结束日期'),
    sa.Column('grade', mysql.VARCHAR(length=20), nullable=False, comment='年级：小班/中班/大班'),
    sa.Column('class_name', mysql.VARCHAR(length=20), nullable=False, comment='班级：1班/2班/3班/4班'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='学期设置',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='学期设置',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('weekly_plans',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学期ID（FK）'),
    sa.Column('week_number', mysql.INTEGER(), autoincrement=False, nullable=False, comment='学期第几周'),
    sa.Column('week_start_date', sa.DATE(), nullable=False, comment='本周首日（周一）'),
    sa.Column('week_end_date', sa.DATE(), nullable=False, comment='本周末日（周五或调休末日）'),
    sa.Column('grade', mysql.VARCHAR(length=20), nullable=False, comment='年级'),
    sa.Column('class_name', mysql.VARCHAR(length=20), nullable=False, comment='班级'),
    sa.Column('theme', mysql.VARCHAR(length=200), server_default=sa.text("''"), nullable=True, comment='本周活动主题'),
    sa.Column('teacher1', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True, comment='教师1（快照）'),
    sa.Column('teacher2', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True, comment='教师2（快照）'),
    sa.Column('carer', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True, comment='保育员（快照）'),
    sa.Column('days_json', mysql.JSON(), nullable=True, comment='5-6天每日活动快照（WeekDayPlan 列表，仅含晨间谈话主题/集体活动名称）'),
    sa.Column('outdoor_game_week', mysql.TEXT(), nullable=True, comment='周级户外游戏（含体能大循环/集体游戏/自主游戏）'),
    sa.Column('area_game_week', mysql.TEXT(), nullable=True, comment='周级区域游戏（含重点指导区域/目标/材料/指导）'),
    sa.Column('week_focus', mysql.TEXT(), nullable=True, comment='本周重点'),
    sa.Column('env_setup', mysql.TEXT(), nullable=True, comment='环境创设'),
    sa.Column('life_habits', mysql.TEXT(), nullable=True, comment='生活习惯培养'),
    sa.Column('home_school', mysql.TEXT(), nullable=True, comment='家园共育'),
    sa.Column('status', mysql.ENUM('draft', 'completed'), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester_settings.id'], name=op.f('weekly_plans_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='周计划',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='周计划',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_weekly_plan'), ['semester_id', 'week_number', 'grade', 'class_name'], unique=True)

    op.create_table('app_settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', mysql.VARCHAR(length=100), nullable=False, comment='设置键'),
    sa.Column('setting_val', mysql.LONGTEXT(), nullable=True, comment='设置值（JSON或纯文本）'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='应用设置',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='应用设置',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('setting_key'), ['setting_key'], unique=True)

    # ### end Alembic commands ###
