"""dev3.0_phase_b_new_tables_and_columns

Revision ID: 54c20d37a461
Revises: d60766786069
Create Date: 2026-06-09 22:51:03.670584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54c20d37a461'
down_revision: Union[str, Sequence[str], None] = 'd60766786069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_observation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('time_range', sa.String(length=64), nullable=True),
    sa.Column('big_env', sa.String(length=8), nullable=False),
    sa.Column('game_area', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('class_name', sa.String(length=32), nullable=True),
    sa.Column('adult_count', sa.Integer(), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('child_names', sa.String(length=255), nullable=True),
    sa.Column('child_age', sa.String(length=64), nullable=True),
    sa.Column('observer', sa.String(length=64), nullable=True),
    sa.Column('observation_goal', sa.Text(), nullable=True),
    sa.Column('observation_record', sa.Text(), nullable=True),
    sa.Column('evaluation_analysis', sa.Text(), nullable=True),
    sa.Column('support_strategy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_observation_tenant_user', 'game_observation', ['tenant_id', 'user_id'], unique=False)
    op.create_table('game_observation_image',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('blob_content', sa.LargeBinary().with_variant(mysql.LONGBLOB(), 'mysql'), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_obs_image_obs_id', 'game_observation_image', ['observation_id'], unique=False)
    op.create_index('ix_game_obs_image_tenant_user', 'game_observation_image', ['tenant_id', 'user_id'], unique=False)
    op.create_table('invite_code',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_invite_code')
    )
    op.create_index(op.f('ix_invite_code_tenant_id'), 'invite_code', ['tenant_id'], unique=False)
    op.add_column('ai_api_key', sa.Column('key_type', sa.Enum('text', 'vision', name='ai_key_type'), server_default=sa.text("'text'"), nullable=False))
    op.add_column('user', sa.Column('display_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    op.drop_column('ai_api_key', 'key_type')
    op.drop_index(op.f('ix_invite_code_tenant_id'), table_name='invite_code')
    op.drop_table('invite_code')
    op.drop_index('ix_game_obs_image_tenant_user', table_name='game_observation_image')
    op.drop_index('ix_game_obs_image_obs_id', table_name='game_observation_image')
    op.drop_table('game_observation_image')
    op.drop_index('ix_game_observation_tenant_user', table_name='game_observation')
    op.drop_table('game_observation')
    # ### end Alembic commands ###
