"""add class_config table

Revision ID: 67b4aef28796
Revises: fd6d29f921b4
Create Date: 2026-05-16 16:59:07.081161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b4aef28796'
down_revision: Union[str, Sequence[str], None] = 'fd6d29f921b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_config',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('indoor_areas', sa.Text(), nullable=True),
    sa.Column('outdoor_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_class_config_tenant_user', 'class_config', ['tenant_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_class_config_tenant_user', table_name='class_config')
    op.drop_table('class_config')
    # ### end Alembic commands ###
