"""add daily_plan table

Revision ID: f6d79ac6bf21
Revises: 46b9fd5613c3
Create Date: 2026-05-17 15:55:01.424684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6d79ac6bf21'
down_revision: Union[str, Sequence[str], None] = '46b9fd5613c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_plan', 'week_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('daily_plan', 'weekday_cn',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4),
               nullable=False)
    op.alter_column('daily_plan', 'grade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False)
    op.alter_column('daily_plan', 'class_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.drop_index(op.f('ix_daily_plan_tenant_user'), table_name='daily_plan')
    op.drop_index(op.f('uq_daily_plan_tenant_user_date'), table_name='daily_plan')
    op.create_index(op.f('ix_daily_plan_tenant_id'), 'daily_plan', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_daily_plan_user_id'), 'daily_plan', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_plan_user_id'), table_name='daily_plan')
    op.drop_index(op.f('ix_daily_plan_tenant_id'), table_name='daily_plan')
    op.create_index(op.f('uq_daily_plan_tenant_user_date'), 'daily_plan', ['tenant_id', 'user_id', 'plan_date'], unique=True)
    op.create_index(op.f('ix_daily_plan_tenant_user'), 'daily_plan', ['tenant_id', 'user_id'], unique=False)
    op.alter_column('daily_plan', 'class_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.alter_column('daily_plan', 'grade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True)
    op.alter_column('daily_plan', 'weekday_cn',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4),
               nullable=True)
    op.alter_column('daily_plan', 'week_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
